server:
  port: 4321
  error:
    include-message: always

logging:
  level:
    root: info

resilience4j:
  retry:
    instances:
      criptoExtremoRetry:
        wait-duration: 2s

schedule:
  timeRequest: '200000'
  cron: '59 59 23 * * ?'

spring:
  url: "v1/api-cripto"
  datasource:
    url: "jdbc:sqlserver://modocripto.database.windows.net:1433;databaseName=modocripto"
    username: "modocripto"
    password: "cr1ptO321"
    driver-class-name: "com.microsoft.sqlserver.jdbc.SQLServerDriver"

coingecko:
  getListCriptoUrl: "https://api.coingecko.com/api/v3/coins/list"
  getExtremosUrl: "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false"
  getHistoryUrl: "https://api.coingecko.com/api/v3/coins/{id}/history"
  getMktRankAllCripto: "https://api.coingecko.com/api/v3/coins/markets"

coinMarketCap:
  apikey: "a7dda90f-54f5-4f51-9b7b-f8257915a41e"
  getLatestValues: "https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?limit=150&convert=USD"



