INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('bitcoin', 'Bitcoin', 1);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('ethereum', 'Ethereum', 2);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('binancecoin', 'Binance Coin', 3);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('cardano', 'Cardano', 4);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('tether', 'Tether', 5);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('ripple', 'XRP', 6);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('solana', 'Solana', 7);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('polkadot', 'Polkadot', 8);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('usd-coin', 'USD Coin', 9);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('dogecoin', 'Dogecoin', 10);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('terra-luna', 'Terra', 11);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('uniswap', 'Uniswap', 12);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('wrapped-bitcoin', 'Wrapped Bitcoin', 13);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('binance-usd', 'Binance USD', 14);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('litecoin', 'Litecoin', 15);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('shiba-inu', 'Shiba Inu', 16);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('chainlink', 'Chainlink', 17);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('avalanche-2', 'Avalanche', 18);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('bitcoin-cash', 'Bitcoin Cash', 19);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('algorand', 'Algorand', 20);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('matic-network', 'Polygon', 21);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('cosmos', 'Cosmos', 22);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('stellar', 'Stellar', 23);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('vechain', 'VeChain', 24);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('axie-infinity', 'Axie Infinity', 25);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('filecoin', 'Filecoin', 26);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('internet-computer', 'Internet Computer', 27);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('ethereum-classic', 'Ethereum Classic', 28);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('tron', 'TRON', 29);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('dai', 'Dai', 30);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('ftx-token', 'FTX Token', 31);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('theta-token', 'Theta Network', 32);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('compound-ether', 'cETH', 33);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('tezos', 'Tezos', 34);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('hedera-hashgraph', 'Hedera', 35);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('staked-ether', 'Lido Staked Ether', 36);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('monero', 'Monero', 37);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('fantom', 'Fantom', 38);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('crypto-com-chain', 'Crypto.com Coin', 39);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('elrond-erd-2', 'Elrond', 40);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('pancakeswap-token', 'PancakeSwap', 41);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('eos', 'EOS', 42);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('okb', 'OKB', 43);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('cdai', 'cDAI', 44);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('near', 'Near', 45);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('the-graph', 'The Graph', 46);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('klay-token', 'Klaytn', 47);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('aave', 'Aave', 48);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('ecash', 'eCash', 49);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('quant-network', 'Quant', 50);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('compound-usd-coin', 'cUSDC', 51);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('bitcoin-cash-abc-2', 'Bitcoin Cash ABC', 52);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('iota', 'IOTA', 53);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('bitcoin-cash-sv', 'Bitcoin SV', 54);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('kusama', 'Kusama', 55);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('neo', 'NEO', 56);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('waves', 'Waves', 57);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('olympus', 'Olympus', 58);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('terrausd', 'TerraUSD', 59);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('arweave', 'Arweave', 60);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('leo-token', 'LEO Token', 61);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('amp-token', 'Amp', 62);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('celsius-degree-token', 'Celsius Network', 63);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('huobi-btc', 'Huobi BTC', 64);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('bittorrent-2', 'BitTorrent', 65);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('harmony', 'Harmony', 66);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('maker', 'Maker', 67);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('sushi', 'Sushi', 68);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('blockstack', 'Stacks', 69);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('thorchain', 'THORChain', 70);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('helium', 'Helium', 71);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('dash', 'Dash', 72);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('omisego', 'OMG Network', 73);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('compound-governance-token', 'Compound', 74);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('celo', 'Celo', 75);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('chiliz', 'Chiliz', 76);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('havven', 'Synthetix Network Token', 77);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('magic-internet-money', 'Magic Internet Money', 78);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('holotoken', 'Holo', 79);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('decred', 'Decred', 80);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('theta-fuel', 'Theta Fuel', 81);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('nem', 'NEM', 82);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('ecomi', 'ECOMI', 83);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('enjincoin', 'Enjin Coin', 84);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('zcash', 'Zcash', 85);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('xdce-crowd-sale', 'XDC Network', 86);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('icon', 'ICON', 87);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('qtum', 'Qtum', 88);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('true-usd', 'TrueUSD', 89);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('telcoin', 'Telcoin', 90);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('yearn-finance', 'yearn.finance', 91);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('dydx', 'dYdX', 92);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('bitcoin-gold', 'Bitcoin Gold', 93);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('zilliqa', 'Zilliqa', 94);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('huobi-token', 'Huobi Token', 95);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('iostoken', 'IOST', 96);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('flow', 'Flow', 97);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('curve-dao-token', 'Curve DAO Token', 98);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('mina-protocol', 'Mina Protocol', 99);
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank) VALUES ('ravencoin', 'Ravencoin', 100);