ALTER TABLE TAB_VALOR_HIST DROP CONSTRAINT FK_TAB_CRIPTO_HIST;

DELETE FROM TAB_VALOR_HIST;

ALTER TABLE TAB_VALOR_HIST DROP COLUMN DataHR_Inc;
ALTER TABLE TAB_VALOR_HIST DROP COLUMN Total_Volume;
ALTER TABLE TAB_VALOR_HIST DROP COLUMN MKT_CAP;
ALTER TABLE TAB_VALOR_HIST DROP COLUMN CRT_PRICE;

ALTER TABLE TAB_VALOR_HIST ADD Open_Price DECIMAL(16,8);
ALTER TABLE TAB_VALOR_HIST ADD Avg_Price DECIMAL(16,8);
ALTER TABLE TAB_VALOR_HIST ADD Close_Price DECIMAL(16,8);
ALTER TABLE TAB_VALOR_HIST ADD Open_Mkt_Cap BIGINT;
ALTER TABLE TAB_VALOR_HIST ADD Avg_Mkt_cap BIGINT;
ALTER TABLE TAB_VALOR_HIST ADD Close_Mkt_Cap BIGINT;
ALTER TABLE TAB_VALOR_HIST ADD Total_Volume BIGINT;
ALTER TABLE TAB_VALOR_HIST ADD Datahr_Inc TIMESTAMP;


ALTER TABLE TAB_VALOR_HIST
    ADD CONSTRAINT FK_TAB_CRIPTO_HIST FOREIGN KEY (ID_Cripto,
                                                   DataHR_Inc) REFERENCES TAB_Valor(ID_Cripto,
                                                                                    DataHR_Inc);