@startuml

title __RESOURCE's Class Diagram__\n

  namespace  {
    namespace om.cripto {
      namespace controller {
        namespace resource {
          interface com.cripto.controller.resource.CriptoExtremosResource {
              {abstract} + getAll()
              {abstract} + getById()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.cripto {
      namespace controller {
        namespace resource {
          interface com.cripto.controller.resource.CriptoValorHistResource {
              {abstract} + getAllDate()
              {abstract} + getDateId()
              {abstract} + getRangeDate()
              {abstract} + getRangeDateId()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.cripto {
      namespace controller {
        namespace resource {
          interface com.cripto.controller.resource.CriptoValorResource {
              {abstract} + getAcimaRank()
              {abstract} + getAll()
              {abstract} + getPorId()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.cripto {
      namespace controller {
        namespace resource {
          interface com.cripto.controller.resource.CriptomoedaResource {
              {abstract} + buscaCriptomoedaPorId()
              {abstract} + buscaTodasCriptomoedas()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.cripto {
      namespace controller {
        namespace resource {
          interface com.cripto.controller.resource.PingResource {
              {abstract} + ping()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
